# Dockerfile
FROM python:3.10-slim

WORKDIR /app

# 1) install deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2) salin source app
COPY app/ /app

# 3) buka port yang akan dipakai
EXPOSE 5000

# 4) jalankan
CMD ["python", "app.py"]
